on: [push, pull_request]

name: Linting

jobs:
  run-linters:
    name: Run pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: 3.8

      - uses: pre-commit/action@v2.0.1
